services:
  server:
    build: .
    container_name: rla_werkx_api
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - 8000:8000
    volumes:
      - .:/app