"""ETL consumed

Revision ID: 0c0d78683776
Revises: 9c5d90fd086f
Create Date: 2026-06-29 10:57:17.389324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c0d78683776'
down_revision: Union[str, Sequence[str], None] = '9c5d90fd086f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_vacation_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_vacation_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('min_years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('days', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
