"""monday morning update

Revision ID: 11b29e85a022
Revises: bb527d8e90e9
Create Date: 2026-06-22 09:46:44.349888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11b29e85a022'
down_revision: Union[str, Sequence[str], None] = 'bb527d8e90e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('lead_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('calendar_holidays', 'region')
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    op.drop_column('employees', 'password_hash')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.add_column('employees', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.add_column('calendar_holidays', sa.Column('region', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True))
    op.drop_table('teams')
    # ### end Alembic commands ###
