"""Check for changes

Revision ID: 267a060f6fbf
Revises: 
Create Date: 2026-02-02 11:06:28.157034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '267a060f6fbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_holidays', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_holidays', sa.Column('region', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True))
    # ### end Alembic commands ###
