"""Added missing relationships

Revision ID: d41ce2f8d7f5
Revises: 17af92011cc6
Create Date: 2026-02-02 14:48:02.673601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd41ce2f8d7f5'
down_revision: Union[str, Sequence[str], None] = '17af92011cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    op.drop_column('employees', 'password_hash')
    op.add_column('projects', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'team_id')
    op.add_column('employees', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'team_id')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
